### PR TITLE
Build argo-actions for local version

### PR DESCRIPTION
**Pull request by lukaszo**
## Description

Changes proposed in this pull request:

- Build argo-actions for local version

### CODE REVIEW

**Comment by mszostok** [comment]
maybe we will remove also the `cloudsql-runner` component as it is not maintained anymore?

Should we also add those images:
- Published on Jun 14 by Capact.io in infra/json-go-gen
- Published on Jun 14 by Capact.io in infra/jinja2
- Published on Jun 14 by Capact.io in infra/graphql-schema-linter

**Comment by lukaszo** [comment]
> * Published on Jun 14 by Capact.io in infra/json-go-gen
> * Published on Jun 14 by Capact.io in infra/jinja2
> * Published on Jun 14 by Capact.io in infra/graphql-schema-linter

This three are not build at the time
```bash
make build-all-apps-images build-all-tests-images
```

**Comment by pkosiec** [comment]
I think we don't need jinja, as we always have fixed version in the manifests. Same with `infra/json-go-gen` and `infra/graphql-schema-linter` - we always use fixed image for all `make` targets and they are not Capact cluster components.

**Comment by mszostok** [comment]
@pkosiec  @lukaszo so maybe we also shouldn't build helm-runner and terraform-runner images? as it's the same story

**Review by mszostok — APPROVED** [review]
🚀

**Review by pkosiec — APPROVED** [review]

**Pull request merged**
